window:
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 10
    y: 10
scrolling:
  # Specifying '0' will disable scrolling.
  history: 100000
  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3
font:
  normal:
    family: Menlo
    style: Regular
  bold:
    family: Menlo
    style: Bold
  italic:
    family: Menlo
    style: Italic
  bold_italic:
    family: Menlo
    style: Bold Italic
  size: 16.0
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true
# Base16 Default Dark 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  primary:
    background: "0x000000"
    foreground: "0xabb2bf"
    bright_foreground: "0xe6efff"
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd8d8d8'
    cursor: '0xd8d8d8'
  normal:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xe6efff"
  # Bright colors
  bright:
    black: '0x585858'
    red: '0xab4642'
    green: '0xa1b56c'
    yellow: '0xf7ca88'
    blue: '0x7cafc2'
    magenta: '0xba8baf'
    cyan: '0x86c1b9'
    white: '0xf8f8f8'
  dim:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xd19a66"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0x828791"
  indexed_colors:
    - { index: 16, color: '0xdc9656' }
    - { index: 17, color: '0xa16946' }
    - { index: 18, color: '0x282828' }
    - { index: 19, color: '0x383838' }
    - { index: 20, color: '0xb8b8b8' }
    - { index: 21, color: '0xe8e8e8' }
# Specifying a `duration` of `0` will disable the visual bell.
bell:
  animation: EaseOutExpo
  duration: 300
  color: '0xffffff'
selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
# Allow terminal applications to change Alacritty’s window title.
window.dynamic_title: true
cursor:
  style: Block
  unfocused_hollow: true
# Live config reload (changes require restart)
live_config_reload: true
# Tell Alacritty that we’re using fish here
shell:
  program: /usr/local/bin/fish
  args:
    - --login
