#!/bin/bash

HOST=$2
VALID_ARGS=$(getopt -o SRr --long setup-nixos,rebuild-nixos,rebuild-home -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

rebuild_nixos() {
	sudo nixos-rebuild switch --flake .#$HOST --show-trace
}

rebuild_home_manager() {
	nix build .#homeConfigurations.$HOST.activationPackage --impure
	echo "Activating build result"
	./result/activate
}


eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    -S | --setup-nixos)
        echo "Initial NixOS setup for host $HOST"
		rebuild_nixos
        shift
        ;;
    -R | --rebuild-nixos)
        echo "Rebuilding NixOS for host $HOST"
        rebuild_nixos
        shift
        ;;
    -r | --rebuild-home)
        echo "Rebuilding home-manager for host $HOST"
        rebuild_home_manager
        shift
        ;;
    --) shift;
        break
        ;;
  esac
done
