#!/usr/bin/env bash

HOST=$2
VALID_ARGS=$(getopt -o SR --long setup-nixos,rebuild-nixos -- "$@")

setup_nixos() {
	local hostname="$1"
	sudo nixos-rebuild switch --flake .#"$hostname" -I nixos-config=hosts/"$hostname"/configuration.nix
}

rebuild_nixos() {
	local hostname="$1"
	sudo nixos-rebuild switch --flake .#"$hostname"
}

eval set -- "$VALID_ARGS"
while true; do
	case "$1" in
	-S | --setup-nixos)
		echo "Initial NixOS setup for host $HOST"
		setup_nixos "$HOST"
		shift
		;;
	-R | --rebuild-nixos)
		echo "Rebuilding NixOS for host $HOST"
		rebuild_nixos "$HOST"
		shift
		;;
	--)
		shift
		break
		;;
	esac
done
