#!/bin/bash

sxhkd &
keynav &
autorandr --change

## Monitor settings
if [[ $(bspc query -M --names | head -n 1) != "eDP" ]]; then
	bspc monitor "DP-0" -d II III IV V VI VII VIII IX X
	bspc monitor "HDMI-0" -d I
fi

bspc config border_width 0.5
bspc config window_gap 2 
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Mouse cursor settings
unclutter -idle 1 -root
xdotool mousemove 999999 999999

# X Compositor
picom --config $HOME/.config/picom/picom.conf &
