#! /bin/sh

sxhkd &

xrandr --output "HDMI-A-0" --primary --mode 1920x1080 --rotate normal --output eDP --mode 1920x1080 --rotate normal --left "HDMI-A-0"

bspc monitor "HDMI-A-0" -d II III IV V VI VII VIII IX X
bspc monitor eDP -d I

bspc config border-width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

unclutter -idle 1 -root &

compton --config ~/.config/compton/compton.conf -b &
